"""

Revision ID: 05074619b84a
Revises: bfed1eb274c3
Create Date: 2025-07-31 13:33:28.688748

"""
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05074619b84a'
down_revision = 'bfed1eb274c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banned_users', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('bots', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('ignored_words', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('jobs', 'bot_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('keywords', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('messages_to_answer', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('monitoring_chats', 'bot_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monitoring_chats', 'bot_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('messages_to_answer', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('keywords', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('jobs', 'bot_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('ignored_words', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('bots', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('banned_users', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###