"""

Revision ID: 05c22016f30f
Revises: 41cd156ac1ae
Create Date: 2025-07-27 22:35:02.685537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05c22016f30f'
down_revision = '41cd156ac1ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banned_users', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('bots', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('ignored_words', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('jobs', 'bot_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('keywords', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('word', table_name='keywords')
    op.alter_column('messages_to_answer', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('monitoring_chats', 'bot_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('users_analyzed', 'bot_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_analyzed', 'bot_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('monitoring_chats', 'bot_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('messages_to_answer', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index('word', 'keywords', ['word'], unique=True)
    op.alter_column('keywords', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('jobs', 'bot_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('ignored_words', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('bots', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('banned_users', 'user_manager_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###