"""

Revision ID: 0db2b1f39946
Revises: bac513b5c236
Create Date: 2025-07-31 18:39:17.037799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db2b1f39946'
down_revision = 'bac513b5c236'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###