"""

Revision ID: 1ad615ff65c4
Revises: 7cbcea71494d
Create Date: 2025-08-14 01:54:48.847399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad615ff65c4'
down_revision = '7cbcea71494d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_analyzed', sa.Column('accepted', sa.Boolean(), nullable=False))
    op.add_column('users_analyzed', sa.Column('decision', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_analyzed', 'decision')
    op.drop_column('users_analyzed', 'accepted')
    # ### end Alembic commands ###