"""

Revision ID: 50262c8a7060
Revises: 0db2b1f39946
Create Date: 2025-08-05 10:10:53.677669

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '50262c8a7060'
down_revision = '0db2b1f39946'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('phone', table_name='bots')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('phone', 'bots', ['phone'], unique=True)
    # ### end Alembic commands ###