"""

Revision ID: 54f9661e18e6
Revises: 1ad615ff65c4
Create Date: 2025-08-14 01:56:11.646575

"""


# revision identifiers, used by Alembic.
revision = '54f9661e18e6'
down_revision = '1ad615ff65c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###