"""

Revision ID: 7cbcea71494d
Revises: 50262c8a7060
Create Date: 2025-08-05 10:13:14.094689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbcea71494d'
down_revision = '50262c8a7060'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('api_id', table_name='bots')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('api_id', 'bots', ['api_id'], unique=True)
    # ### end Alembic commands ###