"""

Revision ID: a5d20209ade0
Revises: ad6bb356c5b6
Create Date: 2025-11-20 19:05:44.604722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d20209ade0'
down_revision = 'ad6bb356c5b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_managers', sa.Column('limit_pack', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_managers', 'limit_pack')
    # ### end Alembic commands ###