"""

Revision ID: ad6bb356c5b6
Revises: 54f9661e18e6
Create Date: 2025-11-20 17:55:57.230023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad6bb356c5b6'
down_revision = '54f9661e18e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_managers', sa.Column('is_antiflood_mode', sa.Boolean(), nullable=False))
    op.drop_index('id_user', table_name='users_analyzed')
    op.drop_column('users_analyzed', 'id_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_analyzed', sa.Column('id_user', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.create_index('id_user', 'users_analyzed', ['id_user'], unique=True)
    op.drop_column('user_managers', 'is_antiflood_mode')
    # ### end Alembic commands ###