"""

Revision ID: bac513b5c236
Revises: 05074619b84a
Create Date: 2025-07-31 17:41:04.835564

"""


# revision identifiers, used by Alembic.
revision = 'bac513b5c236'
down_revision = '05074619b84a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###