"""

Revision ID: bfed1eb274c3
Revises: 05c22016f30f
Create Date: 2025-07-27 22:39:46.904385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfed1eb274c3'
down_revision = '05c22016f30f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id_user', table_name='banned_users')
    op.drop_index('word', table_name='ignored_words')
    op.drop_index('sentence', table_name='messages_to_answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('sentence', 'messages_to_answer', ['sentence'], unique=True)
    op.create_index('word', 'ignored_words', ['word'], unique=True)
    op.create_index('id_user', 'banned_users', ['id_user'], unique=True)
    # ### end Alembic commands ###